### ISSUE TITLE
Error: Requests must originate from GitHub

### ISSUE THREAD

**Issue by roopemerikukka** [Gidgidonihah/github-review-slack-notifier#11]
I'm running this as Docker container and I have set up the applications as the instruction say. when I try to send the GitHub test payload I get following error message:

**Headers**
```
Connection: keep-alive
Content-Length: 147
Content-Type: text/html
Date: Thu, 07 Jun 2018 12:06:50 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=31536000
```

**Body**
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>Requests must originate from GitHub</p>
```

**Comment by Gidgidonihah** [comment]
Sorry for the slow reply. When you say "when I try to send the GitHub test payload" I presume you mean that you are making a direct request to the docker container, not sending a ping from github.

Flask-Hookserver validates all incoming requests and returns a 403 if the request doesn't come from github. This can be turned off with the `GIT_HOOK_VALIDATE_SIGNATURE` and `GIT_HOOK_VALIDATE_IP` env vars.

See https://github.com/Gidgidonihah/github-review-slack-notifier/blob/56ca0f18ede30d4c1d0e1bcb897cd5d6e844670c/app/__init__.py#L9-L10

**Comment by roopemerikukka** [comment]
Nope I tried to deliver the contents of the webhook but got that answer.

I used the ![screen shot 2018-06-13 at 9 43 40](https://user-images.githubusercontent.com/1453463/41334443-4b2451ac-6eee-11e8-83e9-e0b4367091d4.png) button from the webhook so the request should originate from GitHub I presume?

**Comment by roopemerikukka** [comment]
I used your original Docker image and it would be nice to use that and not create onw fork. Would it be possible to add environment variable to the image that could disable the check?

**Comment by Gidgidonihah** [comment]
Ah, so that is being sent from github. Hmm. Well that's unfortunate.

As mentioned, that security is provided by Flask-Hookserver, so I can't alter it here.
And I don't want to change the default behavior to disable the security feature.

If you want to run it with those features turned off, you'll have to build your own image.

**Comment by Gidgidonihah** [comment]
You mentioned you're using the original built docker image. Have you injected `GITHUB_WEBHOOKS_KEY` into the environment? If not, that would cause the error you're seeing by not being able to validate the signature.

**Comment by roopemerikukka** [comment]
Yes I have that environment variable set. I think you don't need to change the default behaviour but there could be one more environment variable like `DISABLE_GITHUB_VERIFICATION` which you could set to true to pass the check. That wouldn't break the existing functionality.

I can also try to create my own image and do some more debugging next week when I have more time :)

**Comment by Gidgidonihah** [comment]
That already exists. Injecting the following env vars and it will disable that security:

```
GIT_HOOK_VALIDATE_IP=false
GIT_HOOK_VALIDATE_SIGNATURE=false
```

**Comment by roopemerikukka** [comment]
Ah okay I need to try those. Thanks!
