### ISSUE TITLE
Server running, JSON received by the server but no output after starting the docker

### ISSUE THREAD

**Issue by Minipada** [Gidgidonihah/github-review-slack-notifier#8]
Hello,
I followed [github webhook tutorial](https://developer.github.com/webhooks/configuring/) and your README but I don't have any print after running the Docker.

I have a sinatra server running containing: 

    require 'sinatra'
    require 'json'

    post '/hooks' do
        request.body.read
    end

I can see on the webhook interface the delivery is successful on the endpoint `http://2860b120.ngrok.io/hooks` and the body is filled with the JSON (echoed by the server). Starting the docker app, nothing is displayed (I added debug option on docker) and no message on Slack. Environment variables have been already checked.

Is there anything I'm missing?

Thanks

**Comment by Gidgidonihah** [comment]
@Minipada Following the github webhook tutorial is not required. You shouldn't have a sinatra server running for this app. I've made some tweaks to the readme which will hopefully clarify what needs to be done to get it up and running.

Sorry it took so very long to respond.

**Comment by Minipada** [comment]
@Gidgidonihah Thanks for the answer, late is better than never.
